language: java
jdk:
  - openjdk11


# используем режим обычного пользователя для сборки проекта.
sudo: false
# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)
# Отправлять уведомление на почту если сборка упала.
notifications:
  email:
    recipients:
      - starslava14@gmail.com
    on_success: never # default: change
    on_failure: always # default: always